baseURL = "/"
title = "Go Figure Math"
languageCode = "en-us"

theme = "mainroad"

paginate = "10" # number of posts per page

googleAnalytics = "" # Enable Google Analytics by entering your tracking id

# [Author] # Used in authorbox
#   name = "THE AMAZING WOMBAT"
#   bio = "Wombat is a mazing. That is what it is. It is exactly one mazing."
#   avatar = "img/avatar.png"

[Params]
  description = "The Elegant Side of Math" # Site description. Used in meta description
  copyright = "Go Figure" # Footer copyright holder, otherwise will use site title
  opengraph = false # Enable OpenGraph if true
  schema = false # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "blog", "news"] # Specify section pages to show on home page and "Recent articles" widget
  dateformat = "January 2, 2006" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js" # Specify MathJax path
  # mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  mathjaxConfig = "TeX-MML-AM_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  themeColor = "#00cc00"
  themeColorLight = "#11dd11"
  themeColorShadow = "#00bb00" 
  menuDarkTextColor = "#3a643b"

  highlightColor = "#ff9900" 
  highlightColorDark = "#f96001"

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/Letterform-Official-Improved-website-header.png" # Logo image. Path relative to "static"
  title = " " # Logo title, otherwise will use site title
  subtitle = " " # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "sidemenu", "recent"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

# [Params.widgets.social]
#   Enable parts of social widget
#   facebook = "username"
#   twitter = "username"
#   instagram = "username"
#   linkedin = "username"
#   telegram = "username"
#   github = "username"
#   gitlab = "username"
#   bitbucket = "username"
#   email = "example@example.com"

# # Custom social links
# [[Params.widgets.social.custom]]
#   title = "Youtube"
#   url = "https://youtube.com/user/username"
#   icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

# [[Params.widgets.social.custom]]
#   title = "My Home Page"
#   url = "http://example.com"


# allow html embedded in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


